apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: website
data:
  default.conf: |
    server {
      listen 8080;
      root /usr/share/nginx/html;
      location / { try_files $uri /index.html; }
      location /kv/ { alias /kv/; default_type application/json; add_header Cache-Control no-store; }
    }
