# Federated to the user-assigned identity lab-dev-website-wi (created by Terraform, aks-bootstrap layer).
# Client ID and tenant ID are identifiers, not secrets.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: website
  namespace: website
  annotations:
    azure.workload.identity/client-id: fe3f1de1-ca08-4745-82f7-da820c8f0d54
    azure.workload.identity/tenant-id: 1c7757cf-6f50-4515-af41-63adb78bae59
